### ISSUE TITLE
Crafting/Trade-up in CS:GO

### ISSUE THREAD

**Issue by raedwulf** [waylaidwanderer/SteamTradeOffersBot#10]
I was looking through the protobufs and the steambot project and noted that bots can craft TF2 items... is the same possible with CSGO?
I know kMsgCraft is in the protobufs for CSGO but other structures like CMsgCraftingResponse are missing. Also the recipe of TF2 crafting doesn't make sense for the trade-up contract in CS:GO...

I was wondering if you had any ideas - thanks in advance!

**Comment by waylaidwanderer** [comment]
Look into [NetHook2](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2). I won't be implementing this myself though.
