### ISSUE TITLE
GetItemDescriptionByClassId fails sometimes when isCurrency is set to false on old items

### ISSUE THREAD

**Issue by hscanlan** [waylaidwanderer/SteamTradeOffersBot#12]
Maybe I'm not clear on what isCurrency does? 

This might not be an issue per say ...

**Comment by waylaidwanderer** [comment]
Can you upload the json response for the inventory in question to pastebin and link it here?

**Comment by hscanlan** [comment]
Yes - hold on, it will take a few minutes to change around the code.

Maybe I'm using GetItemDescriptionByClassID incorrectly - does the item have to exist in my accounts inventory in order to use that function?

**Comment by waylaidwanderer** [comment]
It needs to exist in the inventory that you call the function on.

You can just go to http://steamcommunity.com/profiles/STEAMIDHERE/inventory/json/730/2 to get the JSON response for CSGO, for example.

**Comment by Zexuz** [comment]
Is this not a none existing problem anymore due to PR #23 ?

**Comment by waylaidwanderer** [comment]
I'll close this for now. Feel free to re-open if it's still an issue.
