### ISSUE TITLE
SteamGuardAccount.Session is null

### ISSUE THREAD

**Issue by Retoxified** [waylaidwanderer/SteamTradeOffersBot#13]
An unhandled exception of type 'System.NullReferenceException' occurred in SteamBot.exe
Additional information: Object reference not set to an instance of an object.

SteamGuardAccount.Session is null upon reaching:
SteamGuardAccount.Session.SteamLogin = SteamWeb.Token; // Line 734 of Bot.cs

This is happening with both the nuget version of SteamAuth and a fresh compile from github.

My .auth file contains the following(it's what I dumped back when I was planning to use node-steam)
{"shared_secret":"JxxxxxxxxxxxxxpUxxxxxxx/xxo=","serial_number":"18000000000000000002","revocation_code":"000000","uri":"otpauth://totp/Steam:0000000000000?secret=E50000000000000000000RG0000000E2&issuer=Steam","server_time":"1456917892","account_name":"d000000000002","token_gid":"b00000000000009","identity_secret":"Hxxxxxxxxxxxxxxxxxxxxxxxxxk=","secret_1":"xxxxxxxxxxxxxxxxxxxxxxxxxxx=","status":1}

**Comment by waylaidwanderer** [comment]
You need to link mobile auth via SteamBot. It's a limitation of SteamAuth's design.

**Comment by Retoxified** [comment]
My auth file is the output of 

https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1/
Followed by
https://api.steampowered.com/ITwoFactorService/FinalizeAddAuthenticator/

Which is exactly what the library you're using does, so I don't see how that changes anything. All the info is there and it works fine for any other auth library(node-steam-totp for example).
I have tried adding in the device id, but Session remains null, which is odd to me since I can't even located any place where it would get instantiated in the auth library

**Comment by waylaidwanderer** [comment]
Except it's not "exactly what the library you're using does". SteamAuth does some additional stuff which it serializes into the .auth file. Without it, it will not work.

Trust me on this one.
